package logic;
// Generated 21-sep-2019 0:08:08 by Hibernate Tools 4.3.1



/**
 * AbaaTbOcproyecto generated by hbm2java
 */
public class AbaaTbOcproyecto  implements java.io.Serializable {


     private AbaaTbOcproyectoId id;
     private AbaaProyectos abaaProyectos;
     private SboTbArticulo sboTbArticulo;
     private SboTbOrdenCompra sboTbOrdenCompra;

    public AbaaTbOcproyecto() {
    }

	
    public AbaaTbOcproyecto(AbaaTbOcproyectoId id, AbaaProyectos abaaProyectos, SboTbOrdenCompra sboTbOrdenCompra) {
        this.id = id;
        this.abaaProyectos = abaaProyectos;
        this.sboTbOrdenCompra = sboTbOrdenCompra;
    }
    public AbaaTbOcproyecto(AbaaTbOcproyectoId id, AbaaProyectos abaaProyectos, SboTbArticulo sboTbArticulo, SboTbOrdenCompra sboTbOrdenCompra) {
       this.id = id;
       this.abaaProyectos = abaaProyectos;
       this.sboTbArticulo = sboTbArticulo;
       this.sboTbOrdenCompra = sboTbOrdenCompra;
    }
   
    public AbaaTbOcproyectoId getId() {
        return this.id;
    }
    
    public void setId(AbaaTbOcproyectoId id) {
        this.id = id;
    }
    public AbaaProyectos getAbaaProyectos() {
        return this.abaaProyectos;
    }
    
    public void setAbaaProyectos(AbaaProyectos abaaProyectos) {
        this.abaaProyectos = abaaProyectos;
    }
    public SboTbArticulo getSboTbArticulo() {
        return this.sboTbArticulo;
    }
    
    public void setSboTbArticulo(SboTbArticulo sboTbArticulo) {
        this.sboTbArticulo = sboTbArticulo;
    }
    public SboTbOrdenCompra getSboTbOrdenCompra() {
        return this.sboTbOrdenCompra;
    }
    
    public void setSboTbOrdenCompra(SboTbOrdenCompra sboTbOrdenCompra) {
        this.sboTbOrdenCompra = sboTbOrdenCompra;
    }




}


