package logic;
// Generated 21-sep-2019 0:08:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AbaaProyectos generated by hbm2java
 */
public class AbaaProyectos  implements java.io.Serializable {


     private int proyIdPk;
     private String proyDesc;
     private Set<AbaaTbOcproyecto> abaaTbOcproyectos = new HashSet<AbaaTbOcproyecto>(0);
     private Set<SboTbArticulo> sboTbArticulos = new HashSet<SboTbArticulo>(0);

    public AbaaProyectos() {
    }

	
    public AbaaProyectos(int proyIdPk, String proyDesc) {
        this.proyIdPk = proyIdPk;
        this.proyDesc = proyDesc;
    }
    public AbaaProyectos(int proyIdPk, String proyDesc, Set<AbaaTbOcproyecto> abaaTbOcproyectos, Set<SboTbArticulo> sboTbArticulos) {
       this.proyIdPk = proyIdPk;
       this.proyDesc = proyDesc;
       this.abaaTbOcproyectos = abaaTbOcproyectos;
       this.sboTbArticulos = sboTbArticulos;
    }
   
    public int getProyIdPk() {
        return this.proyIdPk;
    }
    
    public void setProyIdPk(int proyIdPk) {
        this.proyIdPk = proyIdPk;
    }
    public String getProyDesc() {
        return this.proyDesc;
    }
    
    public void setProyDesc(String proyDesc) {
        this.proyDesc = proyDesc;
    }
    public Set<AbaaTbOcproyecto> getAbaaTbOcproyectos() {
        return this.abaaTbOcproyectos;
    }
    
    public void setAbaaTbOcproyectos(Set<AbaaTbOcproyecto> abaaTbOcproyectos) {
        this.abaaTbOcproyectos = abaaTbOcproyectos;
    }
    public Set<SboTbArticulo> getSboTbArticulos() {
        return this.sboTbArticulos;
    }
    
    public void setSboTbArticulos(Set<SboTbArticulo> sboTbArticulos) {
        this.sboTbArticulos = sboTbArticulos;
    }




}


