package logic;
// Generated 21-sep-2019 0:08:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AbaaTbProveedor generated by hbm2java
 */
public class AbaaTbProveedor  implements java.io.Serializable {


     private int proveIdProvePk;
     private String proveCodigo;
     private String proveCedula;
     private Integer proveTelefono;
     private String proveCorreo;
     private String proveFax;
     private String proveNomb;
     private Set<SboTbOrdenCompra> sboTbOrdenCompras = new HashSet<SboTbOrdenCompra>(0);

    public AbaaTbProveedor() {
    }

	
    public AbaaTbProveedor(int proveIdProvePk, String proveNomb) {
        this.proveIdProvePk = proveIdProvePk;
        this.proveNomb = proveNomb;
    }
    public AbaaTbProveedor(int proveIdProvePk, String proveCodigo, String proveCedula, Integer proveTelefono, String proveCorreo, String proveFax, String proveNomb, Set<SboTbOrdenCompra> sboTbOrdenCompras) {
       this.proveIdProvePk = proveIdProvePk;
       this.proveCodigo = proveCodigo;
       this.proveCedula = proveCedula;
       this.proveTelefono = proveTelefono;
       this.proveCorreo = proveCorreo;
       this.proveFax = proveFax;
       this.proveNomb = proveNomb;
       this.sboTbOrdenCompras = sboTbOrdenCompras;
    }
   
    public int getProveIdProvePk() {
        return this.proveIdProvePk;
    }
    
    public void setProveIdProvePk(int proveIdProvePk) {
        this.proveIdProvePk = proveIdProvePk;
    }
    public String getProveCodigo() {
        return this.proveCodigo;
    }
    
    public void setProveCodigo(String proveCodigo) {
        this.proveCodigo = proveCodigo;
    }
    public String getProveCedula() {
        return this.proveCedula;
    }
    
    public void setProveCedula(String proveCedula) {
        this.proveCedula = proveCedula;
    }
    public Integer getProveTelefono() {
        return this.proveTelefono;
    }
    
    public void setProveTelefono(Integer proveTelefono) {
        this.proveTelefono = proveTelefono;
    }
    public String getProveCorreo() {
        return this.proveCorreo;
    }
    
    public void setProveCorreo(String proveCorreo) {
        this.proveCorreo = proveCorreo;
    }
    public String getProveFax() {
        return this.proveFax;
    }
    
    public void setProveFax(String proveFax) {
        this.proveFax = proveFax;
    }
    public String getProveNomb() {
        return this.proveNomb;
    }
    
    public void setProveNomb(String proveNomb) {
        this.proveNomb = proveNomb;
    }
    public Set<SboTbOrdenCompra> getSboTbOrdenCompras() {
        return this.sboTbOrdenCompras;
    }
    
    public void setSboTbOrdenCompras(Set<SboTbOrdenCompra> sboTbOrdenCompras) {
        this.sboTbOrdenCompras = sboTbOrdenCompras;
    }




}


