package logic;
// Generated 22-sep-2019 1:11:19 by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * SboTbSolixArti generated by hbm2java
 */
public class SboTbSolixArti  implements java.io.Serializable {


     private SboTbSolixArtiId id;
    // private SboSicop sboSicop;
     private SboTbSoliArti sboTbSoliArti;
     //private Integer solArtiCant;
     private Date solArtiSali;
     private String solArtiDeta;
     private SboTbExistencia existencia;

    public SboTbSolixArti() {
    }

    public SboTbSolixArti(SboTbSolixArtiId id, SboTbSoliArti sboTbSoliArti, Date solArtiSali, String solArtiDeta, SboTbExistencia existencia) {
        this.id = id;
        this.sboTbSoliArti = sboTbSoliArti;
        this.solArtiSali = solArtiSali;
        this.solArtiDeta = solArtiDeta;
        this.existencia = existencia;
    }

    public SboTbSolixArtiId getId() {
        return id;
    }

    public void setId(SboTbSolixArtiId id) {
        this.id = id;
    }

    public SboTbSoliArti getSboTbSoliArti() {
        return sboTbSoliArti;
    }

    public void setSboTbSoliArti(SboTbSoliArti sboTbSoliArti) {
        this.sboTbSoliArti = sboTbSoliArti;
    }

    public Date getSolArtiSali() {
        return solArtiSali;
    }

    public void setSolArtiSali(Date solArtiSali) {
        this.solArtiSali = solArtiSali;
    }

    public String getSolArtiDeta() {
        return solArtiDeta;
    }

    public void setSolArtiDeta(String solArtiDeta) {
        this.solArtiDeta = solArtiDeta;
    }

    public SboTbExistencia getExistencia() {
        return existencia;
    }

    public void setExistencia(SboTbExistencia existencia) {
        this.existencia = existencia;
    }
     
    
    

}


