package logic;
// Generated 22-sep-2019 1:11:19 by Hibernate Tools 4.3.1



/**
 * SboTbSolixArti generated by hbm2java
 */
public class SboTbSolixArti  implements java.io.Serializable {


     private SboTbSolixArtiId id;
     private SboTbArticulo sboTbArticulo;
     private SboTbSoliArti sboTbSoliArti;
     private Integer solArtiCant;

    public SboTbSolixArti() {
    }

	
    public SboTbSolixArti(SboTbSolixArtiId id, SboTbArticulo sboTbArticulo, SboTbSoliArti sboTbSoliArti) {
        this.id = id;
        this.sboTbArticulo = sboTbArticulo;
        this.sboTbSoliArti = sboTbSoliArti;
    }
    public SboTbSolixArti(SboTbSolixArtiId id, SboTbArticulo sboTbArticulo, SboTbSoliArti sboTbSoliArti, Integer solArtiCant) {
       this.id = id;
       this.sboTbArticulo = sboTbArticulo;
       this.sboTbSoliArti = sboTbSoliArti;
       this.solArtiCant = solArtiCant;
    }
   
    public SboTbSolixArtiId getId() {
        return this.id;
    }
    
    public void setId(SboTbSolixArtiId id) {
        this.id = id;
    }
    public SboTbArticulo getSboTbArticulo() {
        return this.sboTbArticulo;
    }
    
    public void setSboTbArticulo(SboTbArticulo sboTbArticulo) {
        this.sboTbArticulo = sboTbArticulo;
    }
    public SboTbSoliArti getSboTbSoliArti() {
        return this.sboTbSoliArti;
    }
    
    public void setSboTbSoliArti(SboTbSoliArti sboTbSoliArti) {
        this.sboTbSoliArti = sboTbSoliArti;
    }
    public Integer getSolArtiCant() {
        return this.solArtiCant;
    }
    
    public void setSolArtiCant(Integer solArtiCant) {
        this.solArtiCant = solArtiCant;
    }




}


