package logic;
// Generated 22-sep-2019 1:11:19 by Hibernate Tools 4.3.1



/**
 * SboTbCatContable generated by hbm2java
 */
public class SboTbCatContable  implements java.io.Serializable {


     private String cntIdPk;
     private String cntDesc;

    public SboTbCatContable() {
    }

	
    public SboTbCatContable(String cntIdPk) {
        this.cntIdPk = cntIdPk;
    }
    public SboTbCatContable(String cntIdPk, String cntDesc) {
       this.cntIdPk = cntIdPk;
       this.cntDesc = cntDesc;
    }
   
    public String getCntIdPk() {
        return this.cntIdPk;
    }
    
    public void setCntIdPk(String cntIdPk) {
        this.cntIdPk = cntIdPk;
    }
    public String getCntDesc() {
        return this.cntDesc;
    }
    
    public void setCntDesc(String cntDesc) {
        this.cntDesc = cntDesc;
    }




}


