package logic;
// Generated 22-sep-2019 1:11:19 by Hibernate Tools 4.3.1



/**
 * SboTbSolixArtiId generated by hbm2java
 */
public class SboTbSolixArtiId  implements java.io.Serializable {


     private int solixArtiIdSoliArtiPk;
     private int solixArtiIdArtiPk;

    public SboTbSolixArtiId() {
    }

    public SboTbSolixArtiId(int solixArtiIdSoliArtiPk, int solixArtiIdArtiPk) {
       this.solixArtiIdSoliArtiPk = solixArtiIdSoliArtiPk;
       this.solixArtiIdArtiPk = solixArtiIdArtiPk;
    }
   
    public int getSolixArtiIdSoliArtiPk() {
        return this.solixArtiIdSoliArtiPk;
    }
    
    public void setSolixArtiIdSoliArtiPk(int solixArtiIdSoliArtiPk) {
        this.solixArtiIdSoliArtiPk = solixArtiIdSoliArtiPk;
    }
    public int getSolixArtiIdArtiPk() {
        return this.solixArtiIdArtiPk;
    }
    
    public void setSolixArtiIdArtiPk(int solixArtiIdArtiPk) {
        this.solixArtiIdArtiPk = solixArtiIdArtiPk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SboTbSolixArtiId) ) return false;
		 SboTbSolixArtiId castOther = ( SboTbSolixArtiId ) other; 
         
		 return (this.getSolixArtiIdSoliArtiPk()==castOther.getSolixArtiIdSoliArtiPk())
 && (this.getSolixArtiIdArtiPk()==castOther.getSolixArtiIdArtiPk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSolixArtiIdSoliArtiPk();
         result = 37 * result + this.getSolixArtiIdArtiPk();
         return result;
   }   


}


