package logic;
// Generated 21-sep-2019 0:08:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SboTbArticulo generated by hbm2java
 */
public class SboTbArticulo  implements java.io.Serializable {


     private int artIdPk;
     private AbaaProyectos abaaProyectos;
     private AbaaTbDepartamento abaaTbDepartamento;
     private SboTbCatArticulo sboTbCatArticulo;
     private SboTbCatContable sboTbCatContable;
     private SboTbOrdenCompra sboTbOrdenCompra;
     private SboTbSoliArti sboTbSoliArti;
     private Double artPrecio;
     private String artCodContGast;
     private String artCodContExis;
     private String artCodContSal;
     private Date artFvenc;
     private Date artFingr;
     private Date artFsali;
     private Integer artMaxi;
     private Integer artMini;
     private Boolean artEsAc;
     private Integer artLimiDepa;
     private Integer artCantRest;
     private Integer artCant;
     private String artMode;
     private String artNumeSeri;
     private String artMarc;
     private String artNumeFact;
     private String artCodiPresup;
     private String artDesc;
     private String artNumeContra;
     private Set<AbaaTbOcproyecto> abaaTbOcproyectos = new HashSet<AbaaTbOcproyecto>(0);
     private Set<SboTbExistencia> sboTbExistencias = new HashSet<SboTbExistencia>(0);

    public SboTbArticulo() {
    }

	
    public SboTbArticulo(int artIdPk) {
        this.artIdPk = artIdPk;
    }
    public SboTbArticulo(int artIdPk, AbaaProyectos abaaProyectos, AbaaTbDepartamento abaaTbDepartamento, SboTbCatArticulo sboTbCatArticulo, SboTbCatContable sboTbCatContable, SboTbOrdenCompra sboTbOrdenCompra, SboTbSoliArti sboTbSoliArti, Double artPrecio, String artCodContGast, String artCodContExis, String artCodContSal, Date artFvenc, Date artFingr, Date artFsali, Integer artMaxi, Integer artMini, Boolean artEsAc, Integer artLimiDepa, Integer artCantRest, Integer artCant, String artMode, String artNumeSeri, String artMarc, String artNumeFact, String artCodiPresup, String artDesc, String artNumeContra, Set<AbaaTbOcproyecto> abaaTbOcproyectos, Set<SboTbExistencia> sboTbExistencias) {
       this.artIdPk = artIdPk;
       this.abaaProyectos = abaaProyectos;
       this.abaaTbDepartamento = abaaTbDepartamento;
       this.sboTbCatArticulo = sboTbCatArticulo;
       this.sboTbCatContable = sboTbCatContable;
       this.sboTbOrdenCompra = sboTbOrdenCompra;
       this.sboTbSoliArti = sboTbSoliArti;
       this.artPrecio = artPrecio;
       this.artCodContGast = artCodContGast;
       this.artCodContExis = artCodContExis;
       this.artCodContSal = artCodContSal;
       this.artFvenc = artFvenc;
       this.artFingr = artFingr;
       this.artFsali = artFsali;
       this.artMaxi = artMaxi;
       this.artMini = artMini;
       this.artEsAc = artEsAc;
       this.artLimiDepa = artLimiDepa;
       this.artCantRest = artCantRest;
       this.artCant = artCant;
       this.artMode = artMode;
       this.artNumeSeri = artNumeSeri;
       this.artMarc = artMarc;
       this.artNumeFact = artNumeFact;
       this.artCodiPresup = artCodiPresup;
       this.artDesc = artDesc;
       this.artNumeContra = artNumeContra;
       this.abaaTbOcproyectos = abaaTbOcproyectos;
       this.sboTbExistencias = sboTbExistencias;
    }
   
    public int getArtIdPk() {
        return this.artIdPk;
    }
    
    public void setArtIdPk(int artIdPk) {
        this.artIdPk = artIdPk;
    }
    public AbaaProyectos getAbaaProyectos() {
        return this.abaaProyectos;
    }
    
    public void setAbaaProyectos(AbaaProyectos abaaProyectos) {
        this.abaaProyectos = abaaProyectos;
    }
    public AbaaTbDepartamento getAbaaTbDepartamento() {
        return this.abaaTbDepartamento;
    }
    
    public void setAbaaTbDepartamento(AbaaTbDepartamento abaaTbDepartamento) {
        this.abaaTbDepartamento = abaaTbDepartamento;
    }
    public SboTbCatArticulo getSboTbCatArticulo() {
        return this.sboTbCatArticulo;
    }
    
    public void setSboTbCatArticulo(SboTbCatArticulo sboTbCatArticulo) {
        this.sboTbCatArticulo = sboTbCatArticulo;
    }
    public SboTbCatContable getSboTbCatContable() {
        return this.sboTbCatContable;
    }
    
    public void setSboTbCatContable(SboTbCatContable sboTbCatContable) {
        this.sboTbCatContable = sboTbCatContable;
    }
    public SboTbOrdenCompra getSboTbOrdenCompra() {
        return this.sboTbOrdenCompra;
    }
    
    public void setSboTbOrdenCompra(SboTbOrdenCompra sboTbOrdenCompra) {
        this.sboTbOrdenCompra = sboTbOrdenCompra;
    }
    public SboTbSoliArti getSboTbSoliArti() {
        return this.sboTbSoliArti;
    }
    
    public void setSboTbSoliArti(SboTbSoliArti sboTbSoliArti) {
        this.sboTbSoliArti = sboTbSoliArti;
    }
    public Double getArtPrecio() {
        return this.artPrecio;
    }
    
    public void setArtPrecio(Double artPrecio) {
        this.artPrecio = artPrecio;
    }
    public String getArtCodContGast() {
        return this.artCodContGast;
    }
    
    public void setArtCodContGast(String artCodContGast) {
        this.artCodContGast = artCodContGast;
    }
    public String getArtCodContExis() {
        return this.artCodContExis;
    }
    
    public void setArtCodContExis(String artCodContExis) {
        this.artCodContExis = artCodContExis;
    }
    public String getArtCodContSal() {
        return this.artCodContSal;
    }
    
    public void setArtCodContSal(String artCodContSal) {
        this.artCodContSal = artCodContSal;
    }
    public Date getArtFvenc() {
        return this.artFvenc;
    }
    
    public void setArtFvenc(Date artFvenc) {
        this.artFvenc = artFvenc;
    }
    public Date getArtFingr() {
        return this.artFingr;
    }
    
    public void setArtFingr(Date artFingr) {
        this.artFingr = artFingr;
    }
    public Date getArtFsali() {
        return this.artFsali;
    }
    
    public void setArtFsali(Date artFsali) {
        this.artFsali = artFsali;
    }
    public Integer getArtMaxi() {
        return this.artMaxi;
    }
    
    public void setArtMaxi(Integer artMaxi) {
        this.artMaxi = artMaxi;
    }
    public Integer getArtMini() {
        return this.artMini;
    }
    
    public void setArtMini(Integer artMini) {
        this.artMini = artMini;
    }
    public Boolean getArtEsAc() {
        return this.artEsAc;
    }
    
    public void setArtEsAc(Boolean artEsAc) {
        this.artEsAc = artEsAc;
    }
    public Integer getArtLimiDepa() {
        return this.artLimiDepa;
    }
    
    public void setArtLimiDepa(Integer artLimiDepa) {
        this.artLimiDepa = artLimiDepa;
    }
    public Integer getArtCantRest() {
        return this.artCantRest;
    }
    
    public void setArtCantRest(Integer artCantRest) {
        this.artCantRest = artCantRest;
    }
    public Integer getArtCant() {
        return this.artCant;
    }
    
    public void setArtCant(Integer artCant) {
        this.artCant = artCant;
    }
    public String getArtMode() {
        return this.artMode;
    }
    
    public void setArtMode(String artMode) {
        this.artMode = artMode;
    }
    public String getArtNumeSeri() {
        return this.artNumeSeri;
    }
    
    public void setArtNumeSeri(String artNumeSeri) {
        this.artNumeSeri = artNumeSeri;
    }
    public String getArtMarc() {
        return this.artMarc;
    }
    
    public void setArtMarc(String artMarc) {
        this.artMarc = artMarc;
    }
    public String getArtNumeFact() {
        return this.artNumeFact;
    }
    
    public void setArtNumeFact(String artNumeFact) {
        this.artNumeFact = artNumeFact;
    }
    public String getArtCodiPresup() {
        return this.artCodiPresup;
    }
    
    public void setArtCodiPresup(String artCodiPresup) {
        this.artCodiPresup = artCodiPresup;
    }
    public String getArtDesc() {
        return this.artDesc;
    }
    
    public void setArtDesc(String artDesc) {
        this.artDesc = artDesc;
    }
    public String getArtNumeContra() {
        return this.artNumeContra;
    }
    
    public void setArtNumeContra(String artNumeContra) {
        this.artNumeContra = artNumeContra;
    }
    public Set<AbaaTbOcproyecto> getAbaaTbOcproyectos() {
        return this.abaaTbOcproyectos;
    }
    
    public void setAbaaTbOcproyectos(Set<AbaaTbOcproyecto> abaaTbOcproyectos) {
        this.abaaTbOcproyectos = abaaTbOcproyectos;
    }
    public Set<SboTbExistencia> getSboTbExistencias() {
        return this.sboTbExistencias;
    }
    
    public void setSboTbExistencias(Set<SboTbExistencia> sboTbExistencias) {
        this.sboTbExistencias = sboTbExistencias;
    }




}


