package logic;
// Generated 22-sep-2019 1:11:19 by Hibernate Tools 4.3.1



/**
 * SboTbSolixArti generated by hbm2java
 */
public class SboTbSolixArti  implements java.io.Serializable {


     private SboTbSolixArtiId id;
     private SboSicop sboSicop;
     private SboTbSoliArti sboTbSoliArti;
     private Integer solArtiCant;
     private String solArtiSali;

    public SboTbSolixArti() {
    }

	
    public SboTbSolixArti(SboTbSolixArtiId id, SboSicop sboSicop, SboTbSoliArti sboTbSoliArti) {
        this.id = id;
        this.sboSicop = sboSicop;
        this.sboTbSoliArti = sboTbSoliArti;
    }
    public SboTbSolixArti(SboTbSolixArtiId id, SboSicop sboSicop, SboTbSoliArti sboTbSoliArti, Integer solArtiCant, String solArtiSali) {
       this.id = id;
       this.sboSicop = sboSicop;
       this.sboTbSoliArti = sboTbSoliArti;
       this.solArtiCant = solArtiCant;
       this.solArtiSali = solArtiSali;
    }
   
    public SboTbSolixArtiId getId() {
        return this.id;
    }
    
    public void setId(SboTbSolixArtiId id) {
        this.id = id;
    }
    public SboSicop getSboSicop() {
        return this.sboSicop;
    }
    
    public void setSboSicop(SboSicop sboSicop) {
        this.sboSicop = sboSicop;
    }
    public SboTbSoliArti getSboTbSoliArti() {
        return this.sboTbSoliArti;
    }
    
    public void setSboTbSoliArti(SboTbSoliArti sboTbSoliArti) {
        this.sboTbSoliArti = sboTbSoliArti;
    }
    public Integer getSolArtiCant() {
        return this.solArtiCant;
    }
    
    public void setSolArtiCant(Integer solArtiCant) {
        this.solArtiCant = solArtiCant;
    }

    public String getSolArtiSali() {
        return solArtiSali;
    }

    public void setSolArtiSali(String solArtiSali) {
        this.solArtiSali = solArtiSali;
    }

}


