package logic;
// Generated 21-sep-2019 0:08:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SboTbSoliArti generated by hbm2java
 */
public class SboTbSoliArti  implements java.io.Serializable {


     private int solArtiIdPk;
     private AbaaTbDepartamento abaaTbDepartamento;
     private AbaaTbEstado abaaTbEstado;
     private AbaaTbFuncionario abaaTbFuncionario;
     private Double solArtiCant;
     private Boolean solArtiVistJefe;
     private Boolean solArtiVistTi;
     private Date solArtiFechSoli;
     private Set<SboTbArticulo> sboTbArticulos = new HashSet<SboTbArticulo>(0);

    public SboTbSoliArti() {
    }

	
    public SboTbSoliArti(int solArtiIdPk) {
        this.solArtiIdPk = solArtiIdPk;
    }
    public SboTbSoliArti(int solArtiIdPk, AbaaTbDepartamento abaaTbDepartamento, AbaaTbEstado abaaTbEstado, AbaaTbFuncionario abaaTbFuncionario, Double solArtiCant, Boolean solArtiVistJefe, Boolean solArtiVistTi, Date solArtiFechSoli, Set<SboTbArticulo> sboTbArticulos) {
       this.solArtiIdPk = solArtiIdPk;
       this.abaaTbDepartamento = abaaTbDepartamento;
       this.abaaTbEstado = abaaTbEstado;
       this.abaaTbFuncionario = abaaTbFuncionario;
       this.solArtiCant = solArtiCant;
       this.solArtiVistJefe = solArtiVistJefe;
       this.solArtiVistTi = solArtiVistTi;
       this.solArtiFechSoli = solArtiFechSoli;
       this.sboTbArticulos = sboTbArticulos;
    }
   
    public int getSolArtiIdPk() {
        return this.solArtiIdPk;
    }
    
    public void setSolArtiIdPk(int solArtiIdPk) {
        this.solArtiIdPk = solArtiIdPk;
    }
    public AbaaTbDepartamento getAbaaTbDepartamento() {
        return this.abaaTbDepartamento;
    }
    
    public void setAbaaTbDepartamento(AbaaTbDepartamento abaaTbDepartamento) {
        this.abaaTbDepartamento = abaaTbDepartamento;
    }
    public AbaaTbEstado getAbaaTbEstado() {
        return this.abaaTbEstado;
    }
    
    public void setAbaaTbEstado(AbaaTbEstado abaaTbEstado) {
        this.abaaTbEstado = abaaTbEstado;
    }
    public AbaaTbFuncionario getAbaaTbFuncionario() {
        return this.abaaTbFuncionario;
    }
    
    public void setAbaaTbFuncionario(AbaaTbFuncionario abaaTbFuncionario) {
        this.abaaTbFuncionario = abaaTbFuncionario;
    }
    public Double getSolArtiCant() {
        return this.solArtiCant;
    }
    
    public void setSolArtiCant(Double solArtiCant) {
        this.solArtiCant = solArtiCant;
    }
    public Boolean getSolArtiVistJefe() {
        return this.solArtiVistJefe;
    }
    
    public void setSolArtiVistJefe(Boolean solArtiVistJefe) {
        this.solArtiVistJefe = solArtiVistJefe;
    }
    public Boolean getSolArtiVistTi() {
        return this.solArtiVistTi;
    }
    
    public void setSolArtiVistTi(Boolean solArtiVistTi) {
        this.solArtiVistTi = solArtiVistTi;
    }
    public Date getSolArtiFechSoli() {
        return this.solArtiFechSoli;
    }
    
    public void setSolArtiFechSoli(Date solArtiFechSoli) {
        this.solArtiFechSoli = solArtiFechSoli;
    }
    public Set<SboTbArticulo> getSboTbArticulos() {
        return this.sboTbArticulos;
    }
    
    public void setSboTbArticulos(Set<SboTbArticulo> sboTbArticulos) {
        this.sboTbArticulos = sboTbArticulos;
    }




}


