package logic;
// Generated 22-sep-2019 1:11:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SboTbOrdenCompra generated by hbm2java
 */
public class SboTbOrdenCompra  implements java.io.Serializable {


     private int ocIdPk;
     private AbaaTbProveedor abaaTbProveedor;
     private Date ocFecha;
     private Double ocPrecTota;
     private String ocEsta;
     private String ocPlazoEntrega;
     private String ocEntregarA;
     private Set<SboTbArticulo> sboTbArticulos = new HashSet<SboTbArticulo>(0);
     private Set<AbaaTbOcproyecto> abaaTbOcproyectos = new HashSet<AbaaTbOcproyecto>(0);

    public SboTbOrdenCompra() {
    }

	
    public SboTbOrdenCompra(int ocIdPk) {
        this.ocIdPk = ocIdPk;
    }
    public SboTbOrdenCompra(int ocIdPk, AbaaTbProveedor abaaTbProveedor, Date ocFecha, Double ocPrecTota, String ocEsta, String ocPlazoEntrega, String ocEntregarA, Set<SboTbArticulo> sboTbArticulos, Set<AbaaTbOcproyecto> abaaTbOcproyectos) {
       this.ocIdPk = ocIdPk;
       this.abaaTbProveedor = abaaTbProveedor;
       this.ocFecha = ocFecha;
       this.ocPrecTota = ocPrecTota;
       this.ocEsta = ocEsta;
       this.ocPlazoEntrega = ocPlazoEntrega;
       this.ocEntregarA = ocEntregarA;
       this.sboTbArticulos = sboTbArticulos;
       this.abaaTbOcproyectos = abaaTbOcproyectos;
    }
   
    public int getOcIdPk() {
        return this.ocIdPk;
    }
    
    public void setOcIdPk(int ocIdPk) {
        this.ocIdPk = ocIdPk;
    }
    public AbaaTbProveedor getAbaaTbProveedor() {
        return this.abaaTbProveedor;
    }
    
    public void setAbaaTbProveedor(AbaaTbProveedor abaaTbProveedor) {
        this.abaaTbProveedor = abaaTbProveedor;
    }
    public Date getOcFecha() {
        return this.ocFecha;
    }
    
    public void setOcFecha(Date ocFecha) {
        this.ocFecha = ocFecha;
    }
    public Double getOcPrecTota() {
        return this.ocPrecTota;
    }
    
    public void setOcPrecTota(Double ocPrecTota) {
        this.ocPrecTota = ocPrecTota;
    }
    public String getOcEsta() {
        return this.ocEsta;
    }
    
    public void setOcEsta(String ocEsta) {
        this.ocEsta = ocEsta;
    }
    public String getOcPlazoEntrega() {
        return this.ocPlazoEntrega;
    }
    
    public void setOcPlazoEntrega(String ocPlazoEntrega) {
        this.ocPlazoEntrega = ocPlazoEntrega;
    }
    public String getOcEntregarA() {
        return this.ocEntregarA;
    }
    
    public void setOcEntregarA(String ocEntregarA) {
        this.ocEntregarA = ocEntregarA;
    }
    public Set<SboTbArticulo> getSboTbArticulos() {
        return this.sboTbArticulos;
    }
    
    public void setSboTbArticulos(Set<SboTbArticulo> sboTbArticulos) {
        this.sboTbArticulos = sboTbArticulos;
    }
    public Set<AbaaTbOcproyecto> getAbaaTbOcproyectos() {
        return this.abaaTbOcproyectos;
    }
    
    public void setAbaaTbOcproyectos(Set<AbaaTbOcproyecto> abaaTbOcproyectos) {
        this.abaaTbOcproyectos = abaaTbOcproyectos;
    }




}


