package logic;
// Generated 21-sep-2019 0:08:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SboTbBodega generated by hbm2java
 */
public class SboTbBodega  implements java.io.Serializable {


     private int bodeIdPk;
     private AbaaTbFuncionario abaaTbFuncionario;
     private String bodeUbic;
     private String bodeDesc;
     private Set<SboTbExistencia> sboTbExistencias = new HashSet<SboTbExistencia>(0);

    public SboTbBodega() {
    }

	
    public SboTbBodega(int bodeIdPk) {
        this.bodeIdPk = bodeIdPk;
    }
    public SboTbBodega(int bodeIdPk, AbaaTbFuncionario abaaTbFuncionario, String bodeUbic, String bodeDesc, Set<SboTbExistencia> sboTbExistencias) {
       this.bodeIdPk = bodeIdPk;
       this.abaaTbFuncionario = abaaTbFuncionario;
       this.bodeUbic = bodeUbic;
       this.bodeDesc = bodeDesc;
       this.sboTbExistencias = sboTbExistencias;
    }
   
    public int getBodeIdPk() {
        return this.bodeIdPk;
    }
    
    public void setBodeIdPk(int bodeIdPk) {
        this.bodeIdPk = bodeIdPk;
    }
    public AbaaTbFuncionario getAbaaTbFuncionario() {
        return this.abaaTbFuncionario;
    }
    
    public void setAbaaTbFuncionario(AbaaTbFuncionario abaaTbFuncionario) {
        this.abaaTbFuncionario = abaaTbFuncionario;
    }
    public String getBodeUbic() {
        return this.bodeUbic;
    }
    
    public void setBodeUbic(String bodeUbic) {
        this.bodeUbic = bodeUbic;
    }
    public String getBodeDesc() {
        return this.bodeDesc;
    }
    
    public void setBodeDesc(String bodeDesc) {
        this.bodeDesc = bodeDesc;
    }
    public Set<SboTbExistencia> getSboTbExistencias() {
        return this.sboTbExistencias;
    }
    
    public void setSboTbExistencias(Set<SboTbExistencia> sboTbExistencias) {
        this.sboTbExistencias = sboTbExistencias;
    }




}


