package logic;
// Generated 22-sep-2019 1:11:19 by Hibernate Tools 4.3.1



/**
 * SboTbLimiteDptoId generated by hbm2java
 */
public class SboTbLimiteDptoId  implements java.io.Serializable {


     private String limiteDptoIdDptoPk;
     private int limiteDptoIdCatArtiPk;

    public SboTbLimiteDptoId() {
    }

    public SboTbLimiteDptoId(String limiteDptoIdDptoPk, int limiteDptoIdCatArtiPk) {
       this.limiteDptoIdDptoPk = limiteDptoIdDptoPk;
       this.limiteDptoIdCatArtiPk = limiteDptoIdCatArtiPk;
    }
   
    public String getLimiteDptoIdDptoPk() {
        return this.limiteDptoIdDptoPk;
    }
    
    public void setLimiteDptoIdDptoPk(String limiteDptoIdDptoPk) {
        this.limiteDptoIdDptoPk = limiteDptoIdDptoPk;
    }
    public int getLimiteDptoIdCatArtiPk() {
        return this.limiteDptoIdCatArtiPk;
    }
    
    public void setLimiteDptoIdCatArtiPk(int limiteDptoIdCatArtiPk) {
        this.limiteDptoIdCatArtiPk = limiteDptoIdCatArtiPk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SboTbLimiteDptoId) ) return false;
		 SboTbLimiteDptoId castOther = ( SboTbLimiteDptoId ) other; 
         
		 return ( (this.getLimiteDptoIdDptoPk()==castOther.getLimiteDptoIdDptoPk()) || ( this.getLimiteDptoIdDptoPk()!=null && castOther.getLimiteDptoIdDptoPk()!=null && this.getLimiteDptoIdDptoPk().equals(castOther.getLimiteDptoIdDptoPk()) ) )
 && (this.getLimiteDptoIdCatArtiPk()==castOther.getLimiteDptoIdCatArtiPk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLimiteDptoIdDptoPk() == null ? 0 : this.getLimiteDptoIdDptoPk().hashCode() );
         result = 37 * result + this.getLimiteDptoIdCatArtiPk();
         return result;
   }   


}


