package logic;
// Generated 21-sep-2019 0:08:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SboTbCatArticulo generated by hbm2java
 */
public class SboTbCatArticulo  implements java.io.Serializable {


     private int catIdPk;
     private SboTbSubFamilia sboTbSubFamilia;
     private String catCodSicop;
     private String catDesc;
     private Set<SboTbArticulo> sboTbArticulos = new HashSet<SboTbArticulo>(0);

    public SboTbCatArticulo() {
    }

	
    public SboTbCatArticulo(int catIdPk) {
        this.catIdPk = catIdPk;
    }
    public SboTbCatArticulo(int catIdPk, SboTbSubFamilia sboTbSubFamilia, String catCodSicop, String catDesc, Set<SboTbArticulo> sboTbArticulos) {
       this.catIdPk = catIdPk;
       this.sboTbSubFamilia = sboTbSubFamilia;
       this.catCodSicop = catCodSicop;
       this.catDesc = catDesc;
       this.sboTbArticulos = sboTbArticulos;
    }
   
    public int getCatIdPk() {
        return this.catIdPk;
    }
    
    public void setCatIdPk(int catIdPk) {
        this.catIdPk = catIdPk;
    }
    public SboTbSubFamilia getSboTbSubFamilia() {
        return this.sboTbSubFamilia;
    }
    
    public void setSboTbSubFamilia(SboTbSubFamilia sboTbSubFamilia) {
        this.sboTbSubFamilia = sboTbSubFamilia;
    }
    public String getCatCodSicop() {
        return this.catCodSicop;
    }
    
    public void setCatCodSicop(String catCodSicop) {
        this.catCodSicop = catCodSicop;
    }
    public String getCatDesc() {
        return this.catDesc;
    }
    
    public void setCatDesc(String catDesc) {
        this.catDesc = catDesc;
    }
    public Set<SboTbArticulo> getSboTbArticulos() {
        return this.sboTbArticulos;
    }
    
    public void setSboTbArticulos(Set<SboTbArticulo> sboTbArticulos) {
        this.sboTbArticulos = sboTbArticulos;
    }




}


