package logic;
// Generated 22-sep-2019 1:11:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SboTbSoliArti generated by hbm2java
 */
public class SboTbSoliArti  implements java.io.Serializable {


     private int solArtiIdPk;
     private AbaaTbDepartamento abaaTbDepartamento;
     private AbaaTbPersona AbaaTbPersona;
     private Boolean solArtiVistJefe;
     private Boolean solArtiVistTi;
     private Date solArtiFechSoli;
     private Date solArtiFechSali;
     private Set<SboTbSolixArti> sboTbSolixArtis = new HashSet<SboTbSolixArti>(0);
     private String solArtiEsta;
     private String solArtiDesc;
    public SboTbSoliArti() {
    }

	
    public SboTbSoliArti(int solArtiIdPk) {
        this.solArtiIdPk = solArtiIdPk;
    }
    public SboTbSoliArti(int solArtiIdPk, AbaaTbDepartamento abaaTbDepartamento, AbaaTbPersona AbaaTbPersona, Boolean solArtiVistJefe, Boolean solArtiVistTi, Date solArtiFechSoli, Date solArtiFechSali, Set<SboTbSolixArti> sboTbSolixArtis, String solArtiDesc) {
       this.solArtiIdPk = solArtiIdPk;
       this.abaaTbDepartamento = abaaTbDepartamento;
       this.AbaaTbPersona = AbaaTbPersona;
       this.solArtiVistJefe = solArtiVistJefe;
       this.solArtiVistTi = solArtiVistTi;
       this.solArtiFechSoli = solArtiFechSoli;
       this.solArtiFechSali = solArtiFechSali;
       this.sboTbSolixArtis = sboTbSolixArtis;
       this.solArtiDesc=solArtiDesc;
       
    }
   
    public int getSolArtiIdPk() {
        return this.solArtiIdPk;
    }
    
    public void setSolArtiIdPk(int solArtiIdPk) {
        this.solArtiIdPk = solArtiIdPk;
    }
    public AbaaTbDepartamento getAbaaTbDepartamento() {
        return this.abaaTbDepartamento;
    }
    
    public void setAbaaTbDepartamento(AbaaTbDepartamento abaaTbDepartamento) {
        this.abaaTbDepartamento = abaaTbDepartamento;
    }
    public AbaaTbPersona getAbaaTbPersona() {
        return this.AbaaTbPersona;
    }
    
    public void setAbaaTbPersona(AbaaTbPersona abaaTbFuncionario) {
        this.AbaaTbPersona = abaaTbFuncionario;
    }
    public Boolean getSolArtiVistJefe() {
        return this.solArtiVistJefe;
    }
    
    public void setSolArtiVistJefe(Boolean solArtiVistJefe) {
        this.solArtiVistJefe = solArtiVistJefe;
    }
    public Boolean getSolArtiVistTi() {
        return this.solArtiVistTi;
    }
    
    public void setSolArtiVistTi(Boolean solArtiVistTi) {
        this.solArtiVistTi = solArtiVistTi;
    }
    public Date getSolArtiFechSoli() {
        return this.solArtiFechSoli;
    }
    
    public void setSolArtiFechSoli(Date solArtiFechSoli) {
        this.solArtiFechSoli = solArtiFechSoli;
    }
    public Date getSolArtiFechSali() {
        return this.solArtiFechSali;
    }
    
    public void setSolArtiFechSali(Date solArtiFechSali) {
        this.solArtiFechSali = solArtiFechSali;
    }
    public Set<SboTbSolixArti> getSboTbSolixArtis() {
        return this.sboTbSolixArtis;
    }
    
    public void setSboTbSolixArtis(Set<SboTbSolixArti> sboTbSolixArtis) {
        this.sboTbSolixArtis = sboTbSolixArtis;
    }

    public String getSolArtiEsta() {
        return solArtiEsta;
    }

    public void setSolArtiEsta(String solArtiEsta) {
        this.solArtiEsta = solArtiEsta;
    }

    public String getSolArtiDesc() {
        return solArtiDesc;
    }

    public void setSolArtiDesc(String solArtiDesc) {
        this.solArtiDesc = solArtiDesc;
    }

}
