package logic;
// Generated 22-sep-2019 1:11:19 by Hibernate Tools 4.3.1

/**
 * SboTbExistencia generated by hbm2java
 */
public class SboTbExistencia implements java.io.Serializable {

    private SboTbExistenciaId id;
    //private AbaaTbDepartamento abaaTbDepartamento;
    private SboTbBodega sboTbBodega;
    private int SboTbEsta;
    private SboTbArticulo articulo;
   // private SboSicop sboTbSicop;
    //private Double exisCant;
    //private int idE;

    public SboTbExistencia() {
    }

    public SboTbExistencia(SboTbExistenciaId id, SboTbBodega sboTbBodega, int SboTbEsta, SboTbArticulo articulo) {
        this.id = id;
        this.sboTbBodega = sboTbBodega;
        this.SboTbEsta = SboTbEsta;
        this.articulo = articulo;
    }

    public SboTbExistenciaId getId() {
        return id;
    }

    public void setId(SboTbExistenciaId id) {
        this.id = id;
    }

    public SboTbBodega getSboTbBodega() {
        return sboTbBodega;
    }

    public void setSboTbBodega(SboTbBodega sboTbBodega) {
        this.sboTbBodega = sboTbBodega;
    }

    public int getSboTbEsta() {
        return SboTbEsta;
    }

    public void setSboTbEsta(int SboTbEsta) {
        this.SboTbEsta = SboTbEsta;
    }

    public SboTbArticulo getArticulo() {
        return articulo;
    }

    public void setArticulo(SboTbArticulo articulo) {
        this.articulo = articulo;
    }
    
    



}
